kind: project
metadata:
  name: datiprotezione
  created: '2024-07-24T14:07:29.406000'
spec:
  functions:
  - url: src/create-list.py
    name: create-list
    kind: job
    image: mlrun/mlrun
    handler: create_list
    requirements:
    - deep_translator
    - geopandas
  - url: src/convert-list.py
    name: convert-list
    kind: job
    image: mlrun/mlrun
    handler: convert_list
    requirements:
    - geopandas
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/tn-aixpa/datiprotezione.git#refs/heads/main
  origin_url: git://github.com/tn-aixpa/datiprotezione.git#refs/heads/main
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
